changelog:
  categories:
    - title: New
      labels:
        - '*'
      exclude:
        labels:
          - bug
          - change
    - title: Changes
      labels:
        - change
    - title: Bug Fixes
      labels:
        - bug