name: ci-testing
on: [push, pull_request]
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: test
        run: make test
        env:
          VERSION: "v1.0.0"

  testacc:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: testacc
        run: make testacc
        env:
          VERSION: "v1.0.0"
